version: '3.7'

services:

  db-keycloak:
    image: mysql:latest
    container_name: db-keycloak
    restart: always
    volumes:
      - ./mysql-keycloak/dump:/docker-entrypoint-initdb.d    
    environment:
      MYSQL_ROOT_PASSWORD: underground
      MYSQL_DATABASE: keycloak  
    ports:
      - 3307:3306
    networks:
      - stock-manager_net
        
  db-backend:
    image: mysql:latest
    container_name: db-backend
    restart: always
    volumes:
      - ./mysql-backend/dump:/docker-entrypoint-initdb.d      
    environment:
      MYSQL_ROOT_PASSWORD: underground
      MYSQL_DATABASE: training  
    ports:
      - 3306:3306      
    networks:
      - stock-manager_net
        
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    restart: always
    environment:      
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      DB_VENDOR: mysql
      DB_ADDR: db-keycloak
      DB_PORT: 3306
      DB_DATABASE: keycloak
      DB_USER: root
      DB_PASSWORD: underground
    ports:
      - 8081:8080
    networks:
      - stock-manager_net
            
networks:
  stock-manager_net:
    name: stock-manager_net
    driver: bridge      
